---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Contributing

Thank you for considering to contribute to FOSSILPOL, we appreciate the help :sparkling_heart:.
To make sure that we maintain the highest quality of code, we do have to adhere
to some strict guidelines though. Please read through this document to help you get up and running.

If you would like to report a bug, suggest enhancements, or request a new
feature, jump to the [Issues section](#issues).

## Git + GitHub

We use the [Git](https://git-scm.com/) version control system to manage the
development with the repository hosted on [GitHub](https://github.com).
If you are new to Git or GitHub, please read through the
[GitHub Bootcamp](https://help.github.com/categories/bootcamp/) to get up to
speed.

If you're already familiar with Git and GitHub, please read
[Submitting Pull Requests](#submitting-pull-requests).

## Coding Style Guidelines

While we do have our own style in coding and haven't followed any standards available
in the web, we do maintain some uniformity. For contributors, we require the standards
defined in [Advanced R by Hadley Wickham](http://adv-r.had.co.nz/Style.html).

If we missed to mention a particular case, you should always follow the below
procedure:

* See how it's done in the codebase.
* See what Advanced R convention says and choose something that's close to the codebase.
* If all else fails, ask :)

## Submitting Pull Requests

All changes to FOSSILPOL Tools must be in the form of  **pull request** (also known as a PR).
If you are unfamiliar with pull requests, please read
[this](https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project>).

Here is the recommended process:

1. Fork the repo so that you can make your changes without affecting the original project until you're ready to merge them. [Guide to forking](https://docs.github.com/en/get-started/quickstart/fork-a-repo#fork-an-example-repository)
2. Commit your updates once you are happy with them. See contributing [guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#git-commit-messages) to for commit messages.
3. When you're finished with the changes, create a PR
   + Fill in the "Ready for review" template so that we can review your PR. This template helps reviewers understand your changes as well as the purpose of your pull request.
   + Don't forget to [link PR to issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) if you are solving one.
   + Enable the checkbox to [allow maintainer edits](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) so the branch can be updated for a merge. Once you submit your PR, a HOPE team member will review your proposal. We may ask questions or request additional information.
   + We may ask for changes to be made before a PR can be merged, either using suggested changes or pull request comments. You can apply suggested changes directly through the UI. You can make any other changes in your fork, and then commit them to your branch.
As you update your PR and apply changes, mark each conversation as [resolved](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#resolving-conversations)
   + If you run into any merge issues, check out this [git tutorial](https://lab.github.com/githubtraining/managing-merge-conflicts) to help you resolve merge conflicts and other issues.

Before submitting a pull request, please make sure you follow the all guidelines
below while working on your changes:

* Each pull request should try to accomplish one general task.
* All work should be done on a branch with a descriptive name relating to the
  general task (eg. `fix_bug_x` or `add_feature_y`).
* Each individual commit should accomplish one small sub-task and should be
  explainable in a sentence or two.
* Each commit should have a descriptive commit message.
* You should make sure your code passes all tests before committing.

## Issues

Not all contributions have to do with code.
If you would like to report a bug, suggest enhancements, or request a new
feature, please use the [issues page](https://github.com/HOPE-UIB-BIO/FOSSILPOL-workflow/issues) to do so.

If you encounter any issues using this workflow, please use the repository's **Issue** tracker. 

Consider the following steps before and when opening a new Issue:

1. Have you searched for similar issues that may have been already reported? The issue tracker has a filter function to search for keywords in open Issues. You can narrow down the search using `labels`:label: as filters. See [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels) for more information. As a general rule, we don’t assign issues to anyone. 
2. Click on the green **New issue** button in the upper right corner, and describe your problem as detailed as possible. The issue should state what the problem is, what the expected behaviour should be, and, maybe, suggest a solution. Note that you can also attach files or images to the issue.
3. Select a suitable `label`:label: from the drop-down menu called **Labels**.
4. Click on the green **Submit new issue** button and wait for a reply.